### ISSUE TITLE
Error building files

### ISSUE THREAD

**Issue by Robel-AI** [Archargelod/android-lan-play#2]
![Screenshot_20211028-154931](https://user-images.githubusercontent.com/91604855/139250557-7562fcd3-2e19-411a-a0e8-d43e095dd5f5.png)

**Comment by janAkali** [comment]
Could you try again? It's building fine on my phone.
Probably related to recent commits.
I'll add option to build latest stable release. [done]

**Comment by janAkali** [comment]
delete directory switch-lan-play:
`rm -rf ~/switch-lan-play`
update your script and if latest version doesn't compile right now - choose stable when prompted

**Comment by janAkali** [comment]
made some more changes to the script, it was missing binutils, that caused linking error, now it should be fixed.
